### ISSUE TITLE
Kisten sprängen

### ISSUE THREAD

**Issue by AsciiRose** [AsciiRose/Schiffspiel#16]
- Wenn man ein bestimmtes Feld betritt, kann man ein beliebiges Fass/eine beliebige Kiste zerstören -> [Auslöser](https://github.com/AsciiRose/Schiffspiel/issues/12)
- Bei einem Fass, oder einer Kiste handelt es sich um ein bewegliches und zerstörbares Objekt
- Ggf. Zerstörbare Gegenstände hervorheben, wenn man dieses Feld betritt
- Verknüpft mit [Hindernisse](https://github.com/AsciiRose/Schiffspiel/issues/15)

**Comment by jannishinkelmann** [comment]
REJECT
