### ISSUE TITLE
Schiff kippen

### ISSUE THREAD

**Issue by AsciiRose** [AsciiRose/Schiffspiel#17]
- Durch ein bestimmtes Ereignis wird das boot kurz gekippt
- Beispiele für solch ein Ereignis: _(Benötigt Absprache)_
    - Zeitbedingt
    - Anzahl der Züge
    - Zufällig
- Beim Kippen werden die Spielfiguren samt beweglichen Gegenständen _Verschoben_
    -> [Figur bewegen](https://github.com/AsciiRose/Schiffspiel/issues/11)
    -> [Hindernisse](https://github.com/AsciiRose/Schiffspiel/issues/15)
-> Spieler können auf Items rutschen und sie so sammeln
-> Spieler können zueinander rutschen und müssen sich duellieren

**Comment by jannishinkelmann** [comment]
Ist soweit implementiert. Nur das Sammeln von Gegenständen beim Rutschen ist schwierig realisierbar. Das sollte man noch mal überdenken...

**Comment by jannishinkelmann** [comment]
Gegenstände werden von rutschenden Spielern gesammelt.
Das Kippen der Spielfläche horizontal wird automatisch mit entsprechenden Ausgaben getriggert.

**Comment by jannishinkelmann** [comment]
Spieler mit einem Steuer im Inventar können eine Spezialfähigkeit einsetzen, um das Spielfeld nach oben oder nach unten zu kippen.
