### ISSUE TITLE
Namensgebung

### ISSUE THREAD

**Issue by AsciiRose** [AsciiRose/Schiffspiel#18]
- Nach der Auswahl des Levels können sich beide Spieler Namen geben
- Default für Namennn: _Spieler 1 / Spieler 2_ oder _Player 1 / Player 2_
- Verknüpft mit [Startbildschirm](https://github.com/AsciiRose/Schiffspiel/issues/2)
- Verknüpft mit [Levelauswahl](https://github.com/AsciiRose/Schiffspiel/issues/4)

**Comment by AsciiRose** [comment]
NICE TO HAVE

**Comment by jannishinkelmann** [comment]
Mit Commit 18:
Beim Erzeugen eines neuen Spiels erfolgt die Abfrage der Namen der Spieler.
