### ISSUE TITLE
Hauptprogramm

### ISSUE THREAD

**Issue by AsciiRose** [AsciiRose/Schiffspiel#5]
- Erster Entwurf des Spiels
- Grundprinzip mit Buttons und Spielfeld
- Grobe Ideen

**Comment by jannishinkelmann** [comment]
Commit 16:
- Rundenbasierte Spielmechanik:
   - Spieler können abwechselnd würfeln und ziehen
   - Spieler kann nur einmal pro Runde Würfeln
   - Spieler kann nur so oft ziehen wie er Schritte übrig hat
- Spielfeld mit dynamischer Größe
- Objekte können auf dem Feld platziert werden
   - Items sind durch Spieler sammelbar
   - Hindernisse sind möglicherweise verschiebbar

**Comment by AsciiRose** [comment]
@jannishinkelmann da du es hier noch einmal erwähnt hast und es einen sichtbaren stand davon gibt, hab ich [Hindernisse](https://github.com/AsciiRose/Schiffspiel/issues/15) in IN PROGRESS gezogen und deinen Kopf dran gehangen. Wie ist da der Stand?
