### ISSUE TITLE
Würfel

### ISSUE THREAD

**Issue by AsciiRose** [AsciiRose/Schiffspiel#7]
- Erstellen eines Grafischen Würfels
- Zufallszahl zwischen 1 und 6
- Je nach Zufallszahl passendes Bild
- Würfelanimation (nice to have)

**Comment by AsciiRose** [comment]
kannst du den vielleicht auf master schmeißen, damit wir den einbauen können? Sonst machen wir die selbe arbeit erneut @Julian205

**Comment by jannishinkelmann** [comment]
Implementiert (wuefeln-Methode)
