### ISSUE TITLE
Gegenstände einfügen

### ISSUE THREAD

**Issue by AsciiRose** [AsciiRose/Schiffspiel#8]
- Gegenstände ggf. als Liste (oder ähnliches) anlegen
- Gegenstände ins Spielfeld einfügen
- Keine weiteren Aktionen für den ersten Stand
- Nach Muster oder random einfügen (automatisch) -> [Auslöser](https://github.com/AsciiRose/Schiffspiel/issues/12)
- Fehlerbeschränkung (eine Sackgassen)
- Grafische Unterlegung der Gegenstände

**Comment by jannishinkelmann** [comment]
Gegenstände über Methode addFeldObjekt() einfügbar.
